language: python
python:
    - 3.3
    - 3.4
before_install:
    - pip install -r requirements.txt
    - pip install python-coveralls
install:
    python setup.py install
script:
    python setup.py test
after_success:
    coveralls
